[package]
name = "ls"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
file-owner = "0.1.2"
anyhow = "1.0.75"
